### PR TITLE
[Proposal] WIP: Show commands help in colors.

### PR DESCRIPTION
**Pull request by ghost**
It works but I do not know how it would affect translation.

### CODE REVIEW

**Comment by ghost** [comment]
<a href="http://en.zimagez.com/zimage/ncursesfm.php" target="_blank" title="Photo hosted by zimagez.com">Photo hosted by zimagez.com</a>

**Comment by ghost** [comment]
I see, it affects all the translation, I did not realize before :)

**Comment by FedeDP** [comment]
Yeah, i too thought about this thing. But i'd like to come up with an as simple as possible code.
Your idea is good indeed. We only should translate the part of the helper strings without key, eg:
"s -> show stat" will become in msg.po -> "show stat". This way you can:

``` c
 else  { // Description, print normal.
    clrpos += strlen(save[0]);
    mvwprintw(helper_win, y + 1 ,clrpos, "%.*s", COLS - 5,_(save [1]));
    clrpos += strlen(save[1]);
    il = 0;
}
```

Note gettext usage in **_(save[1])** printing!
PS: be aware that COLS-5 is wrong there: that should be COLS - 5 - clrpos ;)

I know it is quite a hard work to remove keys from every string in *.po files. I'm quite busy until tuesday(university exams), after that i'll do that (no need to do that yourself...may be you can test with your own po file to check if i'm right (i hope!) )
Let me know! And thank you very much once more :)

PPS: string_constants.c file would remain untouched, only .po files will change!

**Comment by FedeDP** [comment]
@daltomi Are you still willing to work on this? Otherwise as soon as i've got time i'll merge your code then proceed with fixing things out. Let me know, and thank you very much! :)

**Comment by ghost** [comment]
Sorry but no.
I'm traveling and migrating my system to freebsd and I have no time right now.

Thanks to you :)

**Comment by FedeDP** [comment]
Ok, no problem, i'll finish your work!
Moreover i'd like to make ncursesFM buildable on bsd, so i'll probably try as soon as i've got time!
Btw i hope to see you back soon :)

**Pull request merged**
